Fix git error in Bitrise on telemetry lib upgrading
To increment telemetry library version to just released version the workflow was:
1. Cloning master branch
2. Incrementing the telemetry version
3. Fetching development branch a top those changes
Such order of things can cause git merge conflicts.

Note: This fix is build a top salemove/android-telemetry#92

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -415,8 +415,10 @@ workflows:
                 BASE_BRANCH_NAME="development"
                 MESSAGE="Increment Core SDK version to ${NEW_VERSION}"
                 
-                git fetch origin $BASE_BRANCH_NAME
-                git checkout -b $NEW_BRANCH_NAME origin/$BASE_BRANCH_NAME
+                if [[ "$BITRISE_GIT_BRANCH" != $BASE_BRANCH_NAME ]]; then
+                  echo "❌ Error: this workflow must be run on the ${BASE_BRANCH_NAME} branch to prevent merge conflicts."
+                  exit 1
+                fi
                 git add -A
                 git commit -m "$MESSAGE"
                 git push origin "$NEW_BRANCH_NAME":"$NEW_BRANCH_NAME"
